sudo: required

dist: bionic

language: java

jdk:
  - openjdk11

branches:
  only:
  - 'master'

before_install:
  - nvm install 10
  - nvm use 10
  - node --version

script:
  - ./sbt sandbox${PLATFORM}/run

env:
  matrix:
    - PLATFORM=JS
    - PLATFORM=JVM
